// Comprehensive list of Indonesian provinces and cities
export const PROVINSI_INDONESIA = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Kepulauan Riau",
  "Jambi",
  "Sumatera Selatan",
  "Bangka Belitung",
  "Bengkulu",
  "Lampung",
  "DKI Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Banten",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Sulawesi Tengah",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Gorontalo",
  "Sulawesi Barat",
  "Maluku",
  "Maluku Utara",
  "Papua",
  "Papua Barat",
  "Papua Tengah",
  "Papua Pegunungan",
  "Papua Selatan",
  "Papua Barat Daya"
];

export const KOTA_INDONESIA = [
  // Aceh
  "Banda Aceh",
  "Langsa",
  "Lhokseumawe",
  "Meulaboh",
  "Sabang",
  "Subulussalam",
  
  // Sumatera Utara
  "Medan",
  "Binjai",
  "Pematangsiantar",
  "Sibolga",
  "Tanjungbalai",
  "Tebing Tinggi",
  "Gunungsitoli",
  "Padangsidimpuan",
  
  // Sumatera Barat
  "Padang",
  "Bukittinggi",
  "Padangpanjang",
  "Pariaman",
  "Payakumbuh",
  "Sawahlunto",
  "Solok",
  
  // Riau
  "Pekanbaru",
  "Dumai",
  
  // Kepulauan Riau
  "Batam",
  "Tanjungpinang",
  
  // Jambi
  "Jambi",
  "Sungai Penuh",
  
  // Sumatera Selatan
  "Palembang",
  "Lubuklinggau",
  "Pagar Alam",
  "Prabumulih",
  
  // Bangka Belitung
  "Pangkalpinang",
  
  // Bengkulu
  "Bengkulu",
  
  // Lampung
  "Bandar Lampung",
  "Metro",
  
  // DKI Jakarta
  "Jakarta Pusat",
  "Jakarta Utara",
  "Jakarta Barat",
  "Jakarta Selatan",
  "Jakarta Timur",
  "Kepulauan Seribu",
  
  // Jawa Barat
  "Bandung",
  "Bekasi",
  "Bogor",
  "Cimahi",
  "Cirebon",
  "Depok",
  "Sukabumi",
  "Tasikmalaya",
  "Banjar",
  
  // Jawa Tengah
  "Semarang",
  "Magelang",
  "Pekalongan",
  "Purwokerto",
  "Salatiga",
  "Solo (Surakarta)",
  "Surakarta",
  "Tegal",
  "Klaten",
  "Purwodadi",
  "Wonogiri",
  "Jepara",
  "Kudus",
  "Rembang",
  "Blora",
  "Grobogan",
  "Boyolali",
  "Karanganyar",
  "Sragen",
  "Sukoharjo",
  "Demak",
  "Kendal",
  "Batang",
  "Pekalongan",
  "Pemalang",
  "Tegal",
  "Brebes",
  "Cilacap",
  "Banyumas",
  "Purbalingga",
  "Banjarnegara",
  "Kebumen",
  "Purworejo",
  "Wonosobo",
  "Magelang",
  "Temanggung",
  
  // DI Yogyakarta
  "Yogyakarta",
  "Bantul",
  "Sleman",
  "Kulon Progo",
  "Gunung Kidul",
  
  // Jawa Timur
  "Surabaya",
  "Malang",
  "Batu",
  "Blitar",
  "Kediri",
  "Madiun",
  "Mojokerto",
  "Pasuruan",
  "Probolinggo",
  "Sidoarjo",
  "Gresik",
  "Lamongan",
  "Tuban",
  "Bojonegoro",
  "Ngawi",
  "Magetan",
  "Ponorogo",
  "Pacitan",
  "Trenggalek",
  "Tulungagung",
  "Lumajang",
  "Jember",
  "Banyuwangi",
  "Bondowoso",
  "Situbondo",
  "Pamekasan",
  "Sampang",
  "Sumenep",
  "Bangkalan",
  
  // Banten
  "Serang",
  "Cilegon",
  "Tangerang",
  "Tangerang Selatan",
  "Lebak",
  "Pandeglang",
  
  // Bali
  "Denpasar",
  "Singaraja",
  "Ubud",
  "Sanur",
  "Kuta",
  "Seminyak",
  "Nusa Dua",
  "Jimbaran",
  "Candidasa",
  "Lovina",
  "Amed",
  "Tabanan",
  "Gianyar",
  "Klungkung",
  "Bangli",
  "Karangasem",
  "Buleleng",
  "Jembrana",
  "Badung",
  
  // Nusa Tenggara Barat
  "Mataram",
  "Bima",
  "Dompu",
  "Lombok Barat",
  "Lombok Tengah",
  "Lombok Timur",
  "Lombok Utara",
  "Sumbawa",
  "Sumbawa Barat",
  
  // Nusa Tenggara Timur
  "Kupang",
  "Ende",
  "Maumere",
  "Ruteng",
  "Bajawa",
  "Larantuka",
  "Kalabahi",
  "Waikabubak",
  "Waingapu",
  "Kefamenanu",
  "Atambua",
  
  // Kalimantan Barat
  "Pontianak",
  "Singkawang",
  "Sambas",
  "Sanggau",
  "Sintang",
  "Putussibau",
  "Sekadau",
  "Ngabang",
  "Mempawah",
  "Kubu Raya",
  "Landak",
  "Bengkayang",
  "Ketapang",
  "Sukadana",
  
  // Kalimantan Tengah
  "Palangka Raya",
  "Sampit",
  "Pangkalan Bun",
  "Muara Teweh",
  "Buntok",
  "Kuala Kapuas",
  "Pulang Pisau",
  
  // Kalimantan Selatan
  "Banjarmasin",
  "Banjarbaru",
  "Martapura",
  "Kandangan",
  "Amuntai",
  "Marabahan",
  "Barabai",
  "Rantau",
  "Pelaihari",
  "Kotabaru",
  "Batulicin",
  
  // Kalimantan Timur
  "Samarinda",
  "Balikpapan",
  "Bontang",
  "Tarakan",
  "Berau",
  "Sangatta",
  "Tenggarong",
  "Sendawar",
  "Tanah Grogot",
  
  // Kalimantan Utara
  "Tanjung Selor",
  "Tarakan",
  "Nunukan",
  "Malinau",
  "Bulungan",
  
  // Sulawesi Utara
  "Manado",
  "Bitung",
  "Tomohon",
  "Kotamobagu",
  "Airmadidi",
  "Tondano",
  "Tahuna",
  "Tutuyan",
  "Ratahan",
  
  // Sulawesi Tengah
  "Palu",
  "Poso",
  "Luwuk",
  "Toli-Toli",
  "Donggala",
  "Parigi",
  "Ampana",
  "Buol",
  "Morowali",
  
  // Sulawesi Selatan
  "Makassar",
  "Parepare",
  "Palopo",
  "Watampone",
  "Bulukumba",
  "Bantaeng",
  "Jeneponto",
  "Takalar",
  "Gowa",
  "Sungguminasa",
  "Maros",
  "Pangkep",
  "Barru",
  "Soppeng",
  "Watansoppeng",
  "Wajo",
  "Sengkang",
  "Sidenreng Rappang",
  "Rappang",
  "Pinrang",
  "Enrekang",
  "Tana Toraja",
  "Makale",
  "Toraja Utara",
  "Rantepao",
  "Luwu",
  "Belopa",
  "Luwu Utara",
  "Masamba",
  "Luwu Timur",
  "Malili",
  
  // Sulawesi Tenggara
  "Kendari",
  "Bau-Bau",
  "Raha",
  "Unaaha",
  "Kolaka",
  "Lasusua",
  "Bombana",
  "Rumbia",
  "Konawe",
  "Konawe Selatan",
  "Konawe Utara",
  "Kolaka Utara",
  "Buton",
  "Muna",
  "Wakatobi",
  
  // Gorontalo
  "Gorontalo",
  "Marisa",
  "Tilamuta",
  "Limboto",
  "Kwandang",
  "Suwawa",
  
  // Sulawesi Barat
  "Mamuju",
  "Majene",
  "Polewali",
  "Mamasa",
  "Tobadak",
  "Pasangkayu",
  
  // Maluku
  "Ambon",
  "Tual",
  "Masohi",
  "Namlea",
  "Dobo",
  "Saumlaki",
  "Tiakur",
  "Kairatu",
  "Piru",
  "Tehoru",
  
  // Maluku Utara
  "Ternate",
  "Tidore",
  "Sofifi",
  "Tobelo",
  "Labuha",
  "Sanana",
  "Daruba",
  "Weda",
  
  // Papua
  "Jayapura",
  "Biak",
  "Serui",
  "Nabire",
  "Timika",
  "Merauke",
  "Tanah Merah",
  "Enarotali",
  "Wamena",
  "Sorendiweri",
  "Mulia",
  "Ilaga",
  "Oksibil",
  "Sumohai",
  "Karubaga",
  "Bokondini",
  "Kenyam",
  "Dekai",
  "Ewer",
  "Mamberamo Raya",
  "Mamberamo Tengah",
  "Waropen",
  "Boven Digoel",
  "Mappi",
  "Asmat",
  "Yahukimo",
  "Pegunungan Bintang",
  "Tolikara",
  "Sarmi",
  "Keerom",
  "Yapen",
  "Paniai",
  "Mimika",
  "Puncak Jaya",
  "Puncak",
  "Dogiyai",
  "Intan Jaya",
  "Deiyai",
  "Nduga",
  "Lanny Jaya",
  "Mamberamo Tengah",
  "Yalimo",
  
  // Papua Barat
  "Manokwari",
  "Sorong",
  "Fak-Fak",
  "Kaimana",
  "Teminabuan",
  "Kumurkek",
  "Aimas",
  "Ransiki",
  "Bintuni",
  "Kokoda",
  "Wasior",
  "Waisai",
  
  // Papua Tengah
  "Nabire",
  "Timika",
  "Enarotali",
  "Sugapa",
  "Ilaga",
  
  // Papua Pegunungan
  "Wamena",
  "Mulia",
  "Oksibil",
  "Sumohai",
  "Karubaga",
  "Bokondini",
  
  // Papua Selatan
  "Merauke",
  "Tanah Merah",
  "Kimaam",
  "Okaba",
  "Kurik",
  "Sota",
  
  // Papua Barat Daya
  "Sorong",
  "Teminabuan",
  "Kaimana",
  "Fak-Fak",
  "Kokas",
  "Steenkool",
];

// Helper function to convert arrays to combobox options
export const convertToComboboxOptions = (items: string[]) => 
  items.map(item => ({ value: item, label: item }));
